embeddings:
  api_key: ${OPENAI_API_KEY}
  model: text-embedding-ada-002
  type: openai_embedding
llm:
  api_key: ${OPENAI_API_KEY}
  max_tokens: 4000
  model: gpt-3.5-turbo
  type: openai_chat
storage:
  type: memory
